image : python:3.11
stages:
  - test


variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install build twine
  - pip install hatch
  - pip install pytest-cov


test_job:
  stage: test
  coverage : /TOTAL. * \ s +(\d+\%)$/
  script:
    - echo "Running tests with database service"
    - hatch test --cover
    - pytest --cov=my-arithmetic2-aprigent --cov-report=xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

  tags:
    - docker