image : python:3.11
stages:
  - test
image : ubuntu:latest
test_job:
  stage: test
  script:
    - echo "Running tests with database service"
    - run pip install hatch
    - hatch test
  tags:
    - docker