image : python:3.11
stages:
  - test


variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install build twine
  - pip install hatch
  - python3 -m pip install coverage


test_job:
  stage: test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'  
  script:
    - echo "Running tests with database service"
    - hatch test --cover
    - coverage report -m 
    - coverage xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

  tags:
    - docker